### ISSUE TITLE
Cannot match location by group

### ISSUE THREAD

**Issue by korsarNek** [kaliop-uk/ezmigrationbundle#210]
kaliop/ezmigrationbundle: 5.9.3

Writing a migration for locations with a group match condition throws an error:

Example migration:
```yaml
-
    type: location
    mode: update
    match:
        group: 13 # Editors
    parent_location: 'reference:editor_group_germany_id'
```

stacktrace (paths shortened):
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function matchOneByKey() on null in ./vendor/kaliop/ezmigrationbundle/Core/Matcher/QueryBasedMatcher.php:153
Stack trace:
#0 ./vendor/kaliop/ezmigrationbundle/Core/Matcher/LocationMatcher.php(150): Kaliop\eZMigrationBundle\Core\Matcher\QueryBasedMatcher->getQueryCriterion('group', Array)
#1 ./vendor/kaliop/ezmigrationbundle/Core/Matcher/LocationMatcher.php(91): Kaliop\eZMigrationBundle\Core\Matcher\LocationMatcher->getQueryCriterion('group', Array)
#2 ./vendor/kaliop/ezmigrationbundle/Core/Matcher/LocationMatcherDirectLoad.php(44): Kaliop\eZMigrationBundle\Core\Matcher\LocationMatcher->matchLocation(Array, Array, 0, 0)
#3 ./vendor/kaliop/ezmigrationbundle/Core/Matcher/LocationMatcher.php(47): Kaliop\eZMigrationBundle\Core\Matcher\LocationMatcherDirectLoad->matchLocation(Array,  in ./vendor/kaliop/ezmigrationbundle/Core/Matcher/QueryBasedMatcher.php on line 153
```

The groupMatcher field of the QueryBasedMatcher doesn't seem to be set.

**Comment by gggeek** [comment]
Indeed, there seems to be mistake in the constructor of `QueryBasedMatcher`.
Could you try replacing line 92 with ` $this->groupMatcher = $groupMatcher;` ?

**Comment by korsarNek** [comment]
@gggeek you already closed this ticket? Should I try it out?

**Comment by gggeek** [comment]
Sorry, I was too quick for my own good. You are welcome to test, yes

**Comment by korsarNek** [comment]
PR https://github.com/kaliop-uk/ezmigrationbundle/pull/212
